;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        anzu-query-replace
        comment-line
        company-complete
        dabbrev-expand
        electric-newline-and-maybe-indent
        forward-sexp
        helm-M-x
        helm-show-kill-ring
        indent-for-tab-command
        isearch-backward-regexp
        isearch-exit
        isearch-forward-regexp
        isearch-repeat-backward
        isearch-repeat-forward
        js2-line-break
        kill-region
        markdown-exdent-or-delete
        markdown-outdent-or-delete
        nxml-electric-slash
        org-end-of-line
        org-force-self-insert
        string-inflection-all-cycle
        tern-find-definition
        tern-get-docs
        upcase-region
        wdired-finish-edit
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        backward-kill-sentence
        completion-at-point
        compose-mail
        electric-pair-delete-pair
        eval-print-last-sexp
        find-file
        flycheck-error-list-set-filter
        helm-projectile
        isearch-abort
        isearch-printing-char
        js2-down-mouse-3
        js2-mode-show-node
        magit-status
        mouse-buffer-menu
        mouse-drag-mode-line
        mouse-drag-vertical-line
        mouse-select-window
        mouse-set-region
        next-buffer
        previous-buffer
        push-button
        query-replace
        web-mode-comment-indent-new-line
        ))
