;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        comment-line
        company-complete
        dabbrev-expand
        electric-newline-and-maybe-indent
        forward-sexp
        indent-for-tab-command
        kill-region
        nxml-electric-slash
        tern-find-definition
        upcase-region
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        completion-at-point
        electric-pair-delete-pair
        find-file
        js2-mode-show-node
        mouse-drag-mode-line
        mouse-set-region
        next-buffer
        previous-buffer
        query-replace
        ))
