;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        dabbrev-expand
        electric-newline-and-maybe-indent
        forward-sexp
        indent-for-tab-command
        kill-region
        nxml-electric-slash
        upcase-region
        ))

(setq mc/cmds-to-run-once
      '(
        completion-at-point
        electric-pair-delete-pair
        find-file
        mouse-set-region
        previous-buffer
        ))
