# npm i -g @t1ckbase/vscode-langservers-extracted npm -g install svelte-language-server typescript
[language-server.svelteserver]
command = "svelteserver"
args = ["--stdio"]

[[language]]
name = "svelte"
language-id = "svelte"
file-types = ["svelte"]
roots = ["package.json"]
language-servers = [
  { name = "svelteserver", except-features = [
    "format",
  ], support-workspace = [
    "package.json",
  ] },
  { name = "eslint", support-workspace = true, config-files = [
    ".eslintrc.js",
    ".eslintrc.cjs",
    ".eslintrc.yaml",
    ".eslintrc.yml",
    ".eslintrc",
    ".eslintrc.json",
    "eslint.config.js",
    "eslint.config.mjs",
    "eslint.config.cjs",
    "eslint.config.ts",
    "eslint.config.mts",
    "eslint.config.cts",
  ] },
]

[[language]]
name = "typescript"
language-id = "typescript"
file-types = ["ts", "mts", "cts", "js", "cjs", "mjs"]
roots = ["package.json"]
language-servers = [
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
  { name = "eslint", support-workspace = true, config-files = [
    ".eslintrc.js",
    ".eslintrc.cjs",
    ".eslintrc.yaml",
    ".eslintrc.yml",
    ".eslintrc",
    ".eslintrc.json",
    "eslint.config.js",
    "eslint.config.mjs",
    "eslint.config.cjs",
    "eslint.config.ts",
    "eslint.config.mts",
    "eslint.config.cts",
  ] },
]
